- hosts: localhost
  tasks:
    - name: Display hostnames
      ansible.builtin.debug:
        msg: |
          inventory_hostname: {{ inventory_hostname }}
          ansible_hostname: {{ ansible_hostname }}

    - name: Deploy static /etc/hosts from repository
      ansible.builtin.copy:
        src: files/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
      become: yes

    - name: Install SLURM worker packages on worker nodes
      ansible.builtin.apt:
        name:
          - slurmd
          - munge
        state: present
      become: yes
      when: ansible_hostname is match("^node[0-9]+$")

    - name: Install SLURM control daemon and the client commands on the head
      ansible.builtin.apt:
        name:
          - slurmctld
          - slurm-client
          - munge
        state: present
      become: yes
      when: ansible_hostname == "head"

    - name: Deploy static SLURM config from the repo
      ansible.builtin.copy:
        src: files/slurm.conf
        dest: /etc/slurm/slurm.conf
        owner: slurm
        group: slurm
      become: yes
