ClusterName=gcswtest0

ControlMachine=head
SlurmUser=slurm
AuthType=auth/munge
SelectType=select/cons_res
SelectTypeParameters=CR_CPU
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd

# Logs configuration
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmctldDebug=debug2
SlurmdDebug=debug2

# Quick fix
ProctrackType=proctrack/pgid
TaskPlugin=task/none
JobAcctGatherType=jobacct_gather/none

NodeName=node1 CPUs=1 RealMemory=100 State=UNKNOWN
PartitionName=normal Nodes=node1 Default=YES MaxTime=INFINITE

